# Generated by Django 4.2.12 on 2024-08-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_actual', models.DateTimeField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('precipitaciones', models.FloatField()),
                ('velocidad_viento', models.FloatField()),
            ],
        ),
    ]
